### ISSUE TITLE
Suggested improvements..

### ISSUE THREAD

**Issue by surg0r** [theQRL/offline-wallet-generator#13]
Excellent work so far.

As discussed I think it would be safer to stamp releases with an MD5 / SHA2-256 checksum or equivalent so the downloader can verify independently the release matches what is on their system..

A couple of other minor points:

1) once exported the PDF does not feature a QRL logo - is this by design?
2) adding the possibility for an optional user text label prior to wallet creation which could be seen when the pdf is generated would be useful - users may have several generated offline wallets they use and need to differentiate easily between them
3) perhaps the signature capacity (and less importantly the hash function) may be a useful addition to the output page?

**Comment by jplomas** [comment]
Can these be split into separate issues for triage & implementation planning?
