### ISSUE TITLE
Add release checksum protection

### ISSUE THREAD

**Issue by surg0r** [theQRL/offline-wallet-generator#16]
Users who wish to try the offline wallet generator should have the option to verify an MD5 / SHA2-256 checksum output of what is on their system with the github release.

**Comment by jplomas** [comment]
This is on the roadmap prior to public release.

To ensure the repo has not been compromised and malicious code injected, the hashes will be GPG signed by security@theqrl.org

**Comment by jplomas** [comment]
This has been a feature since v1.6.3 release
